/**
 * Small HTML helpers shared by every page builder.
 */
import { existsSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { dirname, extname, join, relative, sep } from 'node:path';
import sharp from 'sharp';

/** Escape text for HTML, leaving existing named/numeric entities intact. */
export const esc = (s) =>
  String(s ?? '')
    .replace(/&(?![a-z]+;|#\d+;)/gi, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

/** Strip tags and decode the few entities used in content, for meta/JSON. */
export const plain = (s) =>
  String(s ?? '')
    .replace(/<[^>]*>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&nbsp;/g, ' ')
    .replace(/&[lr]squo;|&rsquo;/g, '’')
    .replace(/&mdash;/g, '—')
    .replace(/&ndash;/g, '–')
    .trim();

export const slugify = (s) =>
  plain(s)
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

export const icon = (name, cls = '') =>
  `<svg class="i${cls ? ` ${cls}` : ''}" aria-hidden="true" focusable="false"><use href="/icons.svg#${name}"></use></svg>`;

export const jsonLd = (items) =>
  items
    .filter(Boolean)
    .map((o) => `  <script type="application/ld+json">${JSON.stringify(o)}</script>`)
    .join('\n');

/* ------------------------------------------------------------------ */
/* Images                                                              */
/* ------------------------------------------------------------------ */

const PUBLIC = 'public';
const VARIANT_DIR = join(PUBLIC, '_r');
const VARIANT_WIDTHS = [480, 960, 1440];

const meta = new Map(); // '/images/x.webp' -> { width, height }
const wanted = new Map(); // variant url -> { src, width }

/** Read dimensions of every raster/SVG image in public/ once, before rendering. */
export async function loadImageMeta() {
  const walk = (dir) => {
    for (const name of readdirSync(dir)) {
      const p = join(dir, name);
      if (statSync(p).isDirectory()) {
        if (p !== VARIANT_DIR) walk(p);
        continue;
      }
      const ext = extname(name).toLowerCase();
      if (!['.webp', '.png', '.jpg', '.jpeg', '.svg'].includes(ext)) continue;
      files.push(p);
    }
  };
  const files = [];
  walk(PUBLIC);
  await Promise.all(
    files.map(async (p) => {
      const url = '/' + relative(PUBLIC, p).split(sep).join('/');
      try {
        const m = await sharp(p).metadata();
        meta.set(url, { width: m.width, height: m.height });
      } catch {
        /* unreadable file: rendered without dimensions */
      }
    })
  );
}

const decode = (url) => decodeURI(url);
export const imageSize = (src) => meta.get(decode(src)) || meta.get(src);

/**
 * <img> with intrinsic size (prevents layout shift) and, for large rasters, a
 * srcset of resized WebP variants generated by writeImageVariants().
 */
export function img({ src, alt, sizes = '100vw', cls = '', priority = false, width, height }) {
  const m = imageSize(src) || {};
  const w = width || m.width;
  const h = height || (m.width && width ? Math.round((m.height / m.width) * width) : m.height);
  let srcset = '';
  if (m.width && /\.webp$/i.test(src)) {
    const steps = VARIANT_WIDTHS.filter((v) => v < m.width * 0.9);
    if (steps.length) {
      const set = steps.map((v) => {
        const url = `/_r${decode(src).replace(/\.webp$/i, '')}-${v}.webp`.replace(/ /g, '-');
        wanted.set(url, { src: decode(src), width: v });
        return `${url} ${v}w`;
      });
      set.push(`${src} ${m.width}w`);
      srcset = ` srcset="${esc(set.join(', '))}" sizes="${sizes}"`;
    }
  }
  return `<img src="${esc(src)}"${srcset} alt="${esc(alt)}"${w ? ` width="${w}" height="${h}"` : ''}${
    cls ? ` class="${cls}"` : ''
  }${priority ? ' fetchpriority="high"' : ' loading="lazy"'} decoding="async">`;
}

/** Generate the resized variants referenced while rendering (skips up-to-date files). */
export async function writeImageVariants() {
  let made = 0;
  for (const [url, { src, width }] of wanted) {
    const out = join(PUBLIC, url);
    const input = join(PUBLIC, src);
    if (existsSync(out) && statSync(out).mtimeMs >= statSync(input).mtimeMs) continue;
    mkdirSync(dirname(out), { recursive: true });
    await sharp(input).resize({ width }).webp({ quality: 74, effort: 5 }).toFile(out);
    made++;
  }
  return { total: wanted.size, made };
}

export { VARIANT_DIR };
